import { FastifyPluginAsync } from 'fastify';
import { Octokit } from '@octokit/rest';
import Anthropic from '@anthropic-ai/sdk';
import { buildFingerprintContext } from '../context-builder.js';

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
const anthropicClient = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY || 'dummy_key',
});

export const githubRouter: FastifyPluginAsync = async (app) => {
  app.post('/pr', async (req, reply) => {
    const { projectId, deployId, fingerprint, repoOwner, repoName } = req.body as any;
    
    if (!projectId || !fingerprint || !repoOwner || !repoName) {
      return reply.status(400).send({ error: 'Missing required parameters' });
    }

    const context = await buildFingerprintContext(projectId, fingerprint);
    if (!context) {
      return reply.status(404).send({ error: 'Fingerprint not found' });
    }

    // AI Generation
    const prompt = `
You are analyzing a deployment error.
EXCEPTION: ${context.exceptionType}
STACK: ${context.stackTrace}

Return a JSON object with: { "rootCause": string, "fix": [{ "file": string, "originalCode": string, "fixedCode": string }] }
Make sure the fixedCode represents the ENTIRE file replacement or at least the exact syntax required.
`;

    let generated;
    try {
      const response = await anthropicClient.messages.create({
        model: 'claude-3-5-sonnet-20240620',
        max_tokens: 4096,
        messages: [{ role: 'user', content: prompt }],
      });
      generated = JSON.parse((response.content[0] as any).text);
    } catch (err) {
      app.log.error(err);
      return reply.status(422).send({ error: 'AI generation failed or returned malformed JSON' });
    }

    if (!generated || !Array.isArray(generated.fix) || generated.fix.length === 0) {
      return reply.status(422).send({ error: 'AI returned an empty fix array' });
    }

    // Git Trees API Flow
    try {
      const branchName = `tracepilot-fix-${fingerprint.slice(0, 8)}-${Date.now()}`;
      
      // 1. Get SHA of main branch
      const { data: mainRefData } = await octokit.rest.git.getRef({
        owner: repoOwner,
        repo: repoName,
        ref: 'heads/main',
      });
      const mainSha = mainRefData.object.sha;

      // 2. Create new branch from main
      await octokit.rest.git.createRef({
        owner: repoOwner,
        repo: repoName,
        ref: `refs/heads/${branchName}`,
        sha: mainSha,
      });

      // 3. Fetch SHA from that new branch
      const { data: branchRefData } = await octokit.rest.git.getRef({
        owner: repoOwner,
        repo: repoName,
        ref: `heads/${branchName}`,
      });
      const branchSha = branchRefData.object.sha;

      // 2. Build the tree
      const tree = await Promise.all(generated.fix.map(async (f: any) => {
        // Validation step (stubbed here, assume using acorn or ts API)
        try {
          // e.g., acorn.parse(f.fixedCode, { ecmaVersion: 'latest' })
          // If this throws, we catch and return 422
        } catch (e) {
          throw new Error('Syntax validation failed for file: ' + f.file);
        }

        return {
          path: f.file,
          mode: '100644' as const,
          type: 'blob' as const,
          content: f.fixedCode,
        };
      }));

      const { data: treeData } = await octokit.rest.git.createTree({
        owner: repoOwner,
        repo: repoName,
        base_tree: branchSha,
        tree,
      });

      // 5. Create Commit
      const { data: commitData } = await octokit.rest.git.createCommit({
        owner: repoOwner,
        repo: repoName,
        message: `Fix: ${context.exceptionType}\n\nGenerated by TracePilot.`,
        tree: treeData.sha,
        parents: [branchSha],
      });

      // 4. Update Reference
      await octokit.rest.git.updateRef({
        owner: repoOwner,
        repo: repoName,
        ref: `heads/${branchName}`,
        sha: commitData.sha,
      });

      // 5. Create PR
      const { data: prData } = await octokit.rest.pulls.create({
        owner: repoOwner,
        repo: repoName,
        title: `Fix: ${context.exceptionType}`,
        head: branchName,
        base: 'main',
        body: `### Auto-generated fix by TracePilot\n\n**Error Fingerprint:** \`${fingerprint}\`\n**Root Cause:** ${generated.rootCause}\n\n*Opened by TracePilot on behalf of the user.*`,
      });

      return reply.send({ prUrl: prData.html_url });

    } catch (err: any) {
      app.log.error(err);
      if (err.message?.includes('Syntax validation')) {
         return reply.status(422).send({ error: err.message });
      }
      return reply.status(500).send({ error: 'GitHub flow failed' });
    }
  });
};
