import { FastifyPluginAsync } from 'fastify';
import { Octokit } from '@octokit/rest';
import { GoogleGenerativeAI, Schema, SchemaType } from '@google/generative-ai';
import { buildFingerprintContext } from '../context-builder.js';
import { requireAuth } from '../middleware/auth.js';

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || 'dummy_key');

export const githubRouter: FastifyPluginAsync = async (app) => {
  app.post('/pr', { preHandler: requireAuth }, async (req, reply) => {
    const { projectId, deployId, fingerprint, repoOwner, repoName } = req.body as any;
    
    if (!projectId || !fingerprint || !repoOwner || !repoName) {
      return reply.status(400).send({ error: 'Missing required parameters' });
    }

    const context = await buildFingerprintContext(projectId, fingerprint);
    if (!context) {
      return reply.status(404).send({ error: 'Fingerprint not found' });
    }

    // AI Generation
    const prompt = `
You are analyzing a deployment error.
EXCEPTION: ${context.exceptionType}
STACK: ${context.stackTrace}

Provide the root cause and a code fix. Ensure the fixedCode represents the ENTIRE file replacement or exact syntax.
`;

    const fixSchema: Schema = {
      type: SchemaType.OBJECT,
      properties: {
        rootCause: { type: SchemaType.STRING },
        fix: {
          type: SchemaType.ARRAY,
          items: {
            type: SchemaType.OBJECT,
            properties: {
              file: { type: SchemaType.STRING },
              originalCode: { type: SchemaType.STRING },
              fixedCode: { type: SchemaType.STRING },
            },
            required: ['file', 'originalCode', 'fixedCode']
          }
        }
      },
      required: ['rootCause', 'fix']
    };

    let generated;
    try {
      const model = genAI.getGenerativeModel({ 
        model: 'gemini-2.5-flash',
        generationConfig: {
          responseMimeType: "application/json",
          responseSchema: fixSchema,
        }
      });
      
      const response = await model.generateContent(prompt);
      generated = JSON.parse(response.response.text());
    } catch (err) {
      app.log.error(err);
      return reply.status(422).send({ error: 'AI generation failed or returned malformed JSON' });
    }

    if (!generated || !Array.isArray(generated.fix) || generated.fix.length === 0) {
      return reply.status(422).send({ error: 'AI returned an empty fix array' });
    }

    // Git Trees API Flow
    try {
      const branchName = `tracepilot-fix-${fingerprint.slice(0, 8)}-${Date.now()}`;
      
      // 1. Get SHA of main branch
      const { data: mainRefData } = await octokit.rest.git.getRef({
        owner: repoOwner,
        repo: repoName,
        ref: 'heads/main',
      });
      const mainSha = mainRefData.object.sha;

      // 2. Create new branch from main
      await octokit.rest.git.createRef({
        owner: repoOwner,
        repo: repoName,
        ref: `refs/heads/${branchName}`,
        sha: mainSha,
      });

      // 3. Fetch SHA from that new branch
      const { data: branchRefData } = await octokit.rest.git.getRef({
        owner: repoOwner,
        repo: repoName,
        ref: `heads/${branchName}`,
      });
      const branchSha = branchRefData.object.sha;

      // 4. Build the tree
      const tree = await Promise.all(generated.fix.map(async (f: any) => {
        // Validation step (stubbed here, assume using acorn or ts API)
        try {
          // e.g., acorn.parse(f.fixedCode, { ecmaVersion: 'latest' })
          // If this throws, we catch and return 422
        } catch (e) {
          throw new Error('Syntax validation failed for file: ' + f.file);
        }

        return {
          path: f.file,
          mode: '100644' as const,
          type: 'blob' as const,
          content: f.fixedCode,
        };
      }));

      const { data: treeData } = await octokit.rest.git.createTree({
        owner: repoOwner,
        repo: repoName,
        base_tree: branchSha,
        tree,
      });

      // 5. Create Commit
      const { data: commitData } = await octokit.rest.git.createCommit({
        owner: repoOwner,
        repo: repoName,
        message: `Fix: ${context.exceptionType}\n\nGenerated by TracePilot.`,
        tree: treeData.sha,
        parents: [branchSha],
      });

      // 6. Update Reference
      await octokit.rest.git.updateRef({
        owner: repoOwner,
        repo: repoName,
        ref: `heads/${branchName}`,
        sha: commitData.sha,
      });

      // 7. Create PR
      const { data: prData } = await octokit.rest.pulls.create({
        owner: repoOwner,
        repo: repoName,
        title: `Fix: ${context.exceptionType}`,
        head: branchName,
        base: 'main',
        body: `### Auto-generated fix by TracePilot\n\n**Error Fingerprint:** \`${fingerprint}\`\n**Root Cause:** ${generated.rootCause}\n\n*Opened by TracePilot on behalf of the user.*`,
      });

      return reply.send({ prUrl: prData.html_url });

    } catch (err: any) {
      app.log.error(err);
      if (err.message?.includes('Syntax validation')) {
         return reply.status(422).send({ error: err.message });
      }
      return reply.status(500).send({ error: 'GitHub flow failed' });
    }
  });
};

