import fs from 'fs/promises';
import path from 'path';
import { detectFramework } from './detect-framework.js';

interface InjectionOptions {
  repoPath: string;
  projectId: string;
  deployId: string;
  environment: 'production' | 'preview';
}

export async function injectObservability(opts: InjectionOptions) {
  const framework = await detectFramework(opts.repoPath);

  console.log(`Detected framework: ${framework} — injecting observability`);

  // Step 1: Install the SDK
  await installSDK(opts.repoPath, framework);

  // Step 2: Inject the instrumentation file
  await injectInstrumentationFile(opts.repoPath, framework, opts);

  // Step 3: Modify package.json start script if needed (for Express/Node.js)
  if (framework === 'express' || framework === 'node') {
    await patchStartScript(opts.repoPath);
  }

  console.log('Observability injection complete');
}

async function installSDK(repoPath: string, framework: string) {
  // Add to package.json dependencies programmatically instead of running npm install
  // This avoids slow installs — the platform's build environment will npm install anyway
  const pkgPath = path.join(repoPath, 'package.json');
  const pkg = JSON.parse(await fs.readFile(pkgPath, 'utf8'));

  pkg.dependencies = pkg.dependencies ?? {};
  pkg.dependencies['@swapnil454/tracepilot'] = '^0.1.0';

  await fs.writeFile(pkgPath, JSON.stringify(pkg, null, 2));
}

async function injectInstrumentationFile(
  repoPath: string,
  framework: string,
  opts: InjectionOptions
) {
  if (framework === 'nextjs') {
    // Next.js 14+ supports instrumentation.ts natively
    const content = generateNextInstrumentationFile();
    const filePath = path.join(repoPath, 'instrumentation.ts');

    // If user already has this file, we prepend our init call
    const exists = await fs.access(filePath).then(() => true).catch(() => false);
    if (exists) {
      const existing = await fs.readFile(filePath, 'utf8');
      await fs.writeFile(filePath, mergeInstrumentationFiles(content, existing));
    } else {
      await fs.writeFile(filePath, content);
    }
  }

  if (framework === 'express') {
    // For Express, the script might require @swapnil454/tracepilot/init or something similar
    // We'll leave it out here because we handle it in patchStartScript using --require
  }
}

function mergeInstrumentationFiles(injectedContent: string, existingContent: string): string {
    // A simplified merge: prepend our init and hope it doesn't conflict with their register export.
    // In a production injector, you'd parse AST to safely merge export function register().
    return `${injectedContent}\n\n${existingContent}`;
}

function generateNextInstrumentationFile(): string {
  return `
// Auto-generated by YourPlatform — do not edit manually
export async function register() {
  if (process.env.NEXT_RUNTIME === 'nodejs') {
    const { initTracer, setupGlobalErrorCapture } = await import('@swapnil454/tracepilot');
    initTracer();
    setupGlobalErrorCapture();
  }
}
`.trim();
}

async function patchStartScript(repoPath: string) {
  const pkgPath = path.join(repoPath, 'package.json');
  const pkg = JSON.parse(await fs.readFile(pkgPath, 'utf8'));

  // Prepend --require to the start script so SDK initializes before any user code
  if (pkg.scripts?.start) {
    pkg.scripts.start = pkg.scripts.start.replace(
      /^node /,
      'node --require @swapnil454/tracepilot/express '
    );
  }

  await fs.writeFile(pkgPath, JSON.stringify(pkg, null, 2));
}
