// Code generated by bpf2go; DO NOT EDIT.
//
// This is an IDE/type-checking STUB for non-Linux hosts (Windows/macOS).
// The real version is generated by `go generate ./...` inside the Linux Docker
// builder stage (see Dockerfile, line 9: `RUN go generate ./...`).
//
// Field names and types MUST match what bpf2go produces from xdp_hook.c:
//   - bpfMaps.PingEvents      → *ebpf.Map       (ring-buffer, name "ping_events")
//   - bpfPrograms.XdpPingInterceptor → *ebpf.Program (name "xdp_ping_interceptor")
//
// When `go generate` runs in Docker it overwrites this file with the real output.

//go:build linux

package ebpf

import (
	ciliumebpf "github.com/cilium/ebpf"
)

// bpfObjects contains all objects after they have been loaded into the kernel.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
type bpfMaps struct {
	// PingEvents is the ring-buffer map that xdp_hook.c writes SYN-ACK records into.
	PingEvents *ciliumebpf.Map `ebpf:"ping_events"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(m.PingEvents)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
type bpfPrograms struct {
	// XdpPingInterceptor is the XDP program attached to the network interface.
	XdpPingInterceptor *ciliumebpf.Program `ebpf:"xdp_ping_interceptor"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(p.XdpPingInterceptor)
}

func _BpfClose(closers ...interface{ Close() error }) error {
	for _, c := range closers {
		if c == nil {
			continue
		}
		if err := c.Close(); err != nil {
			return err
		}
	}
	return nil
}

// loadBpfObjects loads the compiled BPF object file into the kernel and populates obj.
// opts may be nil. Generated by bpf2go; this stub panics at runtime on Linux if the
// real generated file is not present.
func loadBpfObjects(obj *bpfObjects, opts *ciliumebpf.CollectionOptions) error {
	panic("loadBpfObjects stub called — run `go generate ./...` inside the Docker builder to produce the real bpf_bpfel.go")
}
