name: Publish JavaScript SDK to NPM

on:
  release:
    types: [published]

jobs:
  publish-js-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        working-directory: packages/sdk
        run: npm install

      - name: Build JavaScript SDK
        working-directory: packages/sdk
        run: npm run build

      - name: Publish JavaScript SDK
        working-directory: packages/sdk
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
